coverage:
  precision: 2
  round: down
  range: "70...100"

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

ignore:
  - "tests"
  - "examples"
